#define TOKEN_PLUS                            1
#define TOKEN_MINUS                           2
#define TOKEN_TIMES                           3
#define TOKEN_DIV                             4
#define TOKEN_LESS                            5
#define TOKEN_LESS_EQ                         6
#define TOKEN_EQ                              7
#define TOKEN_NOT_EQ                          8
#define TOKEN_GREATER                         9
#define TOKEN_GREATER_EQ                     10
#define TOKEN_UNARY_NEG                      11
#define TOKEN_OR                             12
#define TOKEN_AND                            13
#define TOKEN_NOT                            14
#define TOKEN_GREATSPN_MEASURE               15
#define TOKEN_END                            16
#define TOKEN_GREATSPN_MDEPDELAY             17
#define TOKEN_GREATSPN_MDEARCMULT            18
#define TOKEN_GREATSPN_TRNGUARD              19
#define TOKEN_GREATSPN_GENERALPDF            20
#define TOKEN_DTA_EDGE_DEF                   21
#define TOKEN_DTA_STATE_PROPOSITION          22
#define TOKEN_DTA_BINDING_RULES              23
#define TOKEN_CSLTA_EXPR                     24
#define TOKEN_INVALID                        25
#define TOKEN_SEMICOLON                      26
#define TOKEN_REALNUM                        27
#define TOKEN_INTEGER                        28
#define TOKEN_G_RATE_PARAM                   29
#define TOKEN_G_MARK_PARAM                   30
#define TOKEN_SHARP                          31
#define TOKEN_G_PLACE_ID                     32
#define TOKEN_OP_PAREN                       33
#define TOKEN_CL_PAREN                       34
#define TOKEN_OP_SQPAR                       35
#define TOKEN_COMMA                          36
#define TOKEN_CL_SQPAR                       37
#define TOKEN_IF_FN                          38
#define TOKEN_WHEN                           39
#define TOKEN_COLON                          40
#define TOKEN_EVER                           41
#define TOKEN_ABS_FN                         42
#define TOKEN_FACTORIAL_FN                   43
#define TOKEN_MIN_FN                         44
#define TOKEN_MAX_FN                         45
#define TOKEN_MOD_FN                         46
#define TOKEN_BINOMIAL_FN                    47
#define TOKEN_FRACT_FN                       48
#define TOKEN_PDF_X_VAR                      49
#define TOKEN_LOG_FN                         50
#define TOKEN_SIN_FN                         51
#define TOKEN_COS_FN                         52
#define TOKEN_TAN_FN                         53
#define TOKEN_ARCSIN_FN                      54
#define TOKEN_ARCCOS_FN                      55
#define TOKEN_ARCTAN_FN                      56
#define TOKEN_EXP_FN                         57
#define TOKEN_SQRT_FN                        58
#define TOKEN_CEIL_FN                        59
#define TOKEN_FLOOR_FN                       60
#define TOKEN_DIRACDELTA_FN                  61
#define TOKEN_POW_FN                         62
#define TOKEN_RECT_FN                        63
#define TOKEN_UNIFORM_FN                     64
#define TOKEN_TRIANGULAR_FN                  65
#define TOKEN_ERLANG_FN                      66
#define TOKEN_TRUNCATED_EXP_FN               67
#define TOKEN_PARETO_FN                      68
#define TOKEN_TRUE                           69
#define TOKEN_FALSE                          70
#define TOKEN_OPEN_P                         71
#define TOKEN_CL_BRACK                       72
#define TOKEN_OPEN_E                         73
#define TOKEN_OPEN_X                         74
#define TOKEN_G_TRANSITION_ID                75
#define TOKEN_G_ACTION_ID                    76
#define TOKEN_ACTS                           77
#define TOKEN_SETMINUS                       78
#define TOKEN_OP_BRACK                       79
#define TOKEN_G_CLOCKVALUE_ID                80
#define TOKEN_XCLK                           81
#define TOKEN_RESET                          82
#define TOKEN_G_ATOMIC_PROP_ID               83
#define TOKEN_ID                             84
#define TOKEN_STRING                         85
#define TOKEN_PROB_TA                        86
